Task9.ASP.NET_App/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Task9.ASP.NET_App.Data;
using Task9.ASP.NET_App.Data.Interface;
using Task9.ASP.NET_App.Data.Models;
using Task9.ASP.NET_App.Data.Services;

namespace Task9.ASP.NET_App.Controllers
{
    public class CourseController : Controller
    {

        private readonly ICourseService _courseService;


        public CourseController(ICourseService courseService)
        {
            this._courseService = courseService;

        }

        public ViewResult ShowCourse()
        {
            ViewBag.Tile = "Courses";
            var course = _courseService.GetAllCourse;
            return View(course);
        }

        public ViewResult EditCourse(int id)
        {
            ViewBag.Title = "Edit Course";
            var course = _courseService.GetCourseByID(id);
            if(course != null)
            {

                return View(course);
            }
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult SaveEdit(Course course)
        {
            bool result = _courseService.SaveEdit(course);
            if (result)
            {
                ViewBag.Message = "Successfully!";
            }
            else
            {
                ViewBag.Message = "Error,try again!";
            }
            return View();
        }

        public ActionResult DeleteCourse(int id)
        {
            bool result = _courseService.DeleteCourse(id);
            if (result)
            {
                ViewBag.Message = "Successfully!";
            }
            else
            {
                ViewBag.Message = "Error,Can not delete course with group inside,or course do not exist!";
            }
            
            return View();
        }

 

        public ActionResult AddCourse()
        {
            return View();

        }

        


    }
}

Task9.ASP.NET_App/Controllers/GroupController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Task9.ASP.NET_App.Data.Interface;
using Task9.ASP.NET_App.Data.Models;
using Task9.ASP.NET_App.Data;
using Task9.ASP.NET_App.Data.Services;

namespace Task9.ASP.NET_App.Controllers
{
    public class GroupController : Controller
    {
        private readonly IGroupService _groupService;
        private readonly ICourseService _courseService;

        public GroupController(IGroupService groupService ,ICourseService courseService)
        {
            this._groupService = groupService;
            this._courseService = courseService;

        }


        public ViewResult CourseGroups(int id)
        {
            ViewBag.Title = "Groups";
            var cours = _courseService.GetCourseByID(id);
            if(cours != null)
            {
                ViewBag.CourseName = cours.Name;
                var groups = _groupService.GetGroupByCourseID(id);
                ViewBag.CourseId = id;
                if (groups == null)
                {
                    return View();
                }

                return View(groups);
            }
            return View();
        }
       
       public ViewResult Edit(int id)
        {
            var group = _groupService.GetGroupByID(id);
            return View(group);
        }

        [HttpPost,ValidateAntiForgeryToken]
        public ActionResult Save(Group group)
        {
            bool result = _groupService.Save(group);
            if (result)
            {
                ViewBag.Message = "Successfully!";
            }
            else
            {
                ViewBag.Message = "Error ,try again!";
            }
            return View(group);
        }

        public ViewResult Delete(int id)
        {
            var group = _groupService.GetGroupByID(id);
            bool result = _groupService.Delete(id);
            if (result)
            {
                ViewBag.CourseId = group.CourseId;
                ViewBag.Message = "Successfully!";
            }
            else
            {
                ViewBag.Message = "Error,can not delete group with students,or group do not exist!";
            }
            return View();
        }

        public ViewResult AddGroup(int courseId)
        {
            ViewBag.CourseId = courseId;
            return View();
        }

    }
}

Task9.ASP.NET_App/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Task9.ASP.NET_App.Data;
using Task9.ASP.NET_App.Data.Interface;
using Task9.ASP.NET_App.Data.Models;
using Task9.ASP.NET_App.Data.Services;

namespace Task9.ASP.NET_App.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentService _studentService;
        private readonly IGroupService _groupService;

        public StudentController(IStudentService studentService,IGroupService groupService)
        {
            this._studentService = studentService;
            this._groupService = groupService;
        }

        public ViewResult ShowStudents(int id)
        {
            ViewBag.Title = "Students";
            var group = _groupService.GetGroupByID(id);
            if(group != null)
            {
                ViewBag.CourseId = group.CourseId;
                var studetns = _studentService.GetStudentsByGroupID(id);
                ViewBag.GroupID = id;
                ViewBag.GroupName = group.Name;
                return View(studetns);
            }
            return View();
            
        }

        public ViewResult Edit(int id)
        {
            ViewBag.Title = "Edit Students";
            var student = _studentService.GetStudentByID(id);
            return View(student);
        }

        [HttpPost,ValidateAntiForgeryToken]

        public ActionResult Save(Student student)
        {
            bool result = _studentService.Save(student);
            if (result)
            {
                ViewBag.Message = "Successfully!";
            }
            else
            {
                ViewBag.Message = "Error,try again!";
            }
            return View(student);
        }

        public ActionResult Delete(int id)
        {
            var student = _studentService.GetStudentByID(id);
            bool result = _studentService.Delete(id);
            if (result)
            {
                ViewBag.Message = "Successfully!";
            }
            else
            {
                ViewBag.Message = "Error,try again!";
            }
            return View(student);
        }

        public ViewResult AddNewStudent(int groupId)
        {
            ViewBag.groupId = groupId;
            return View();
        }
    }
}

Task9.ASP.NET_App/Views/Course/AddCourse.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Add new course</h1>
@using (Html.BeginForm("SaveEdit", "Course", FormMethod.Post))
{
    <div style="display : flex">
        <p>
            Input course name:
            <input type="text" name="Name" value="" style="height:30px;width:100px;"/>
        </p>
    </div>
    <div style="display : flex">
        <p>
            Input course description:
            <input type="text" name="Description" value="" style="height:30px;width:100px;"/>
        </p>
    </div>
    <input type="submit" value="Add"  style="height:30px;margin-right:15px;" />
    <button  style="height:30px;">@Html.ActionLink("Cancel","ShowCourse","Course")</button>
}

Task9.ASP.NET_App/Views/Course/DeleteCourse.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>@ViewBag.Message</h1>
<button>@Html.ActionLink("Go to course", "ShowCourse")</button>

Task9.ASP.NET_App/Views/Course/EditCourse.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


    @using (Html.BeginForm("SaveEdit", "Course", FormMethod.Post))
    {
        if (Model != null)
        {
            <h2>Edit @Model.Name course</h2>
            <input type="hidden" value="@Model.Id" name="Id" />
            <div style="display : flex ;">
                <p style="font-size:18px">Input new name:<input type="text" name="Name" value="@Model.Name" style="width:100px;height:30px;" /></p>
            </div>
            <div style="display : flex;">
                <p style="font-size:18px;">Input new description:<input type="text" name="Description" value="@Model.Description" style="width:100px;height:30px;" /></p>
            </div>
            <div style="display : flex;">
                <input type="submit" value="Save" style="font-size:20px;margin-right:15px;" />
                <button style="font-size:20px;">@Html.ActionLink("Cancel", "ShowCourse", "Course")</button>
            </div>
        }
        else
        {
            <p>Course do not exist!</p>
            <button style="width:120px;height:30px;">@Html.ActionLink("Back to course","ShowCourse","Course")</button>
        }

    }

Task9.ASP.NET_App/Views/Course/SaveEdit.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>@ViewBag.Message</h1>
<button>@Html.ActionLink("Go to course","ShowCourse", "Course")</button>

Task9.ASP.NET_App/Views/Course/ShowCourse.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>All Course:</h1>


@{  if (Model != null) { 
        foreach (var course in Model)
        {
        <div style="display : flex">
            <p>
                @course.Name (@course.Description)
                <button style="width:60px;height:30px; margin-right:15px;">@Html.ActionLink("Groups", "CourseGroups", "Group", new { id = course.Id })</button>
                <button style="width: 60px; height: 30px; margin-right: 15px;">@Html.ActionLink("Edit", "EditCourse", "Course", new { id = course.Id })</button>
                <button style="width:60px;height:30px;">@Html.ActionLink("Delete", "DeleteCourse", "Course", new { id = course.Id })</button>
            </p>
        </div>
        <br>
        }
    }
    }     
    <button style="width:120px;height:30px;">@Html.ActionLink("Add new Course", "AddCourse", "Course")</button>

Task9.ASP.NET_App/Views/Group/AddGroup.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Add new Group</h1>
@using (Html.BeginForm("Save","Group",FormMethod.Post)) { 
    <input type="hidden" value="@ViewBag.CourseId" name="CourseId"/>
    <div style="display : flex">
        <p>
            Input Group Name
            <input type="text" name="Name" style="height:30px;width:100px;"/>
        </p>
    </div>
    <div style="display : flex">
        <input type="submit" value="Save" style="height:30px;margin-right:15px;"/>
        <button style="height:30px;">@Html.ActionLink("Cancel", "CourseGroups", "Group" , new {id=ViewBag.CourseId })</button>
    </div>
}

Task9.ASP.NET_App/Views/Group/CourseGroups.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    if (Model != null)
    {
        <h1>@ViewBag.CourseName course groups:</h1>
        foreach (var group in Model)
        {
            <div style="display : flex">
                <p>
                    @group.Name
                    <button style="width: 80px; height: 30px; margin-right: 15px;">@Html.ActionLink("Students", "ShowStudents", "Student", new { id = group.Id }) </button>
                    <button style="width: 80px; height: 30px; margin-right: 15px;">@Html.ActionLink("Edit", "Edit", "Group", new { id = group.Id })</button>
                    <button style="width: 80px; height: 30px; margin-right: 15px;">@Html.ActionLink("Delete", "Delete", "Group", new { id = group.Id })</button>
                </p>
            </div>
            <br>
        }
        <div style="display:flex">
            <button style="width: 120px; height: 30px; margin-right: 15px;">@Html.ActionLink("Add Group", "AddGroup", "Group", new { courseId = ViewBag.CourseId })</button>
            <button style="width: 120px; height: 30px;">@Html.ActionLink("Back to course", "ShowCourse", "Course")</button>
        </div>
    }
    else
    {
        <p>Course do not exist!</p>
        <button style="width: 120px; height: 30px;"> @Html.ActionLink("Back to course", "ShowCourse", "Course")</button>
    }

}

Task9.ASP.NET_App/Views/Group/Delete.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>@ViewBag.Message</h1>
<button>@Html.ActionLink("Go back", "CourseGroups", "Group" , new {id = ViewBag.CourseId })</button>

Task9.ASP.NET_App/Views/Group/Edit.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Save", "Group"))
{
    if (Model != null)
    {
        <h1>Edit @Model.Name</h1>
        <input type="hidden" value="@Model.Id" name="Id" />
        <input type="hidden" value="@Model.CourseId" name="CourseId">
        <div style="display : flex">
            <p>
                Write new name
                <input type="text" name="Name" value="@Model.Name" style="width:100px;height:30px;" />
            </p>
        </div>
        <div style="display : flex">
            <input type="submit" value="Save" style="height:30px;margin-right:15px;" />
            <button style="height:30px;">@Html.ActionLink("Cancel", "CourseGroups", "Group", new { id = Model.CourseId })</button>
        </div>
    }
    else
    {
        <p>Group do not exist!</p>
        <button style="width:120px;height:30px;">@Html.ActionLink("Back to course","ShowCourse","Course")</button>
    }


}

Task9.ASP.NET_App/Views/Group/Save.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>@ViewBag.Message</h1>
<button>@Html.ActionLink("Go back", "CourseGroups", "Group",new {id = Model.CourseId })</button>

Task9.ASP.NET_App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/wwwroot/site.css")" rel="stylesheet" type="text/css" />
    
</head>
<body>
    
    @RenderBody()

</body>
</html>

Task9.ASP.NET_App/Views/Student/AddNewStudent.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Add new Student</h1>
@using (Html.BeginForm("Save", "Student", FormMethod.Post))
{
    <input type="hidden" value="@ViewBag.GroupID" name="GroupID"/>
    <div style="display:flex">
        <p>
            Input first name
            <input type="text" name="FirstName" value="" style="height:30px;width:100px;"/>
        </p>
    </div>
    <div style="display :flex">
        <p>Input last name</p>
        <input type="text" name="LastName" value="" style="height:30px;width:100px;"/>       
    </div>
    <div style="display:flex">
        <input type="submit" value="Save" style="height:30px;margin-right:15px;" />
        <button style="height:30px;">@Html.ActionLink("Cancel", "ShowStudents", "Student" , new {id = ViewBag.GroupID })</button>
    </div>
}

Task9.ASP.NET_App/Views/Student/Delete.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>@ViewBag.Message</h1>
@{ if (Model != null)
    {

        <button>@Html.ActionLink("Go Back", "ShowStudents", "Student", new { id = Model.GroupID })</button>
    }
    else
    {
        <p>Student do not exist!</p>
        <button>@Html.ActionLink("Back to course","ShowCourse","Course")</button>
    }
}

Task9.ASP.NET_App/Views/Student/Edit.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Save", "Student", FormMethod.Post))
{
    if (Model != null)
    {
        <h1>Edit @Model.FirstName @Model.LastName</h1>
        <input type="hidden" value="@Model.Id" name="Id" />
        <input type="hidden" value="@Model.GroupID" name="GroupID" />
        <div>
            <div style="display : flex">
                <p>
                    Input new name:
                    <input type="text" name="FirstName" value="@Model.FirstName" style="height:30px;width:100px;" />
                </p>
            </div>

            <div style="display:flex">
                <p>
                    Input new last name:
                    <input type="text" name="LastName" value="@Model.LastName" style="height:30px;width:100px;" />
                </p>
            </div>
        </div>
        <div style="display:flex">
            <input type="submit" value="Save" style="height:30px;margin-right:15px;" />
            <button style="height:30px;">@Html.ActionLink("Cancel", "ShowStudents", "Student", new { id = Model.GroupID })</button>
        </div>
    }
    else
    {
        <p>Student do not exist!</p>
        <button>@Html.ActionLink("Back to course","ShowCourse","Course")</button>
    }

}

Task9.ASP.NET_App/Views/Student/Save.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>@ViewBag.Message</h1>
<button>@Html.ActionLink("Go Back","ShowStudents","Student" , new {id = Model.GroupID })</button>

Task9.ASP.NET_App/Views/Student/ShowStudents.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{ if (Model != null)
    {
        <h1>@ViewBag.GroupName Student</h1>
        foreach (var student in Model)
        {
            <div style="display : flex">
                <p>
                    @student.FirstName @student.LastName
                    <button style="height:30px;width:60px;margin-right:15px;">@Html.ActionLink("Edit", "Edit", "Student", new { id = student.Id })</button>
                    <button style="height:30px;width:60px;">@Html.ActionLink("Delete", "Delete", "Student", new { id = student.Id })</button>
                </p>
            </div>
            <br>

        }
        <div style="display : flex">

            <button style="height:30px;margin-right:15px">@Html.ActionLink("Add new student", "AddNewStudent", "Student", new { groupId = ViewBag.GroupID })</button>
            <button style="height:30px;">@Html.ActionLink("Go back", "CourseGroups", "Group", new { id = ViewBag.CourseId })</button>
        </div>
    }
    else
    {
        <p>Group do not exist!</p>
        <button style="width:120px;height:30px;">@Html.ActionLink("Back to course", "ShowCourse", "Course")</button>
    }

}